import type { Project, Device } from "@/types";

const projects: Project[] = [
    {
      id: 'project-1',
      userId: '1',
      name: 'Projeto 1',
      description: 'Descrição do projeto 1',
      visibility: 'public',
      tags: ['tag1', 'tag2'],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'project-2',
      userId: '1',
      name: 'Projeto 2',
      description: 'Descrição do projeto 2',
      visibility: 'public',
      tags: ['tag3', 'tag4'],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'project-3',
      userId: '1',
      name: 'Projeto 3',
      description: 'Descrição do projeto 3',
      visibility: 'private',
      tags: ['tag5'],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
]

const devices: Device[] = [
    {
      id: 'device-1',
      projectId: 'project-1',
      name: 'Dispositivo 1',
      description: 'Descrição do dispositivo 1',
      serialNumber: '1234567890',
      deviceType: 'actuator',
      status: 'online',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      cultura: 'soja',
      vazao: '10.5',
      lat: '-23.5505',
      longitude: '-46.6333',
    },
    {
      id: 'device-2',
      projectId: 'project-1',
      name: 'Dispositivo 2',
      description: 'Descrição do dispositivo 2',
      serialNumber: '1234567891',
      deviceType: 'actuator',
      status: 'online',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'device-3',
      projectId: 'project-2',
      name: 'Dispositivo 3',
      description: 'Descrição do dispositivo 3',
      serialNumber: '1234567892',
      deviceType: 'actuator',
      status: 'online',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'device-4',
      projectId: 'project-2',
      name: 'Dispositivo 4',
      description: 'Descrição do dispositivo 4',
      serialNumber: '1234567893',
      deviceType: 'actuator',
      status: 'offline',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'device-5',
      projectId: 'project-3',
      name: 'Dispositivo 5',
      description: 'Descrição do dispositivo 5',
      serialNumber: '1234567894',
      deviceType: 'actuator',
      status: 'online',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      cultura: 'milho',
      vazao: '8.2',
      lat: '-22.9068',
      longitude: '-43.1729',
    },
    {
      id: 'device-6',
      projectId: 'project-3',
      name: 'Dispositivo 6',
      description: 'Descrição do dispositivo 6',
      serialNumber: '1234567895',
      deviceType: 'actuator',
      status: 'offline',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ]

export { projects, devices }
