export { HomePage } from './Home'
export { ProjectsPage } from './Projects'
export { ActuatorPage } from './Actuator'
export { DevicePage } from './Device'
export { SettingsPage } from './Settings'
export { NotFoundPage } from './NotFound'